#pragma once

// Setup FOGL_AUTO_STATE_CHECKING

#ifndef FOGL_FORCE_NO_AUTO_STATE_CHECKING
#ifndef NDEBUG
#ifndef FOGL_AUTO_STATE_CHECKING
#define FOGL_AUTO_STATE_CHECKING
#endif
#endif
#endif

#ifdef FOGL_FORCE_AUTO_STATE_CHECKING
#ifndef FOGL_AUTO_STATE_CHECKING
#define FOGL_AUTO_STATE_CHECKING
#endif
#endif

// Setup FOGL_AUTO_ERROR_CHECKING

#ifndef FOGL_FORCE_NO_AUTO_ERROR_CHECKING
#ifndef NDEBUG
#ifndef FOGL_AUTO_ERROR_CHECKING
#define FOGL_AUTO_ERROR_CHECKING
#endif
#endif
#endif

#ifdef FOGL_FORCE_AUTO_ERROR_CHECKING
#ifndef FOGL_AUTO_ERROR_CHECKING
#define FOGL_AUTO_ERROR_CHECKING
#endif
#endif

// Setup FOGL_AUTO_NULL_CHECKING

#ifndef FOGL_FORCE_NO_AUTO_NULL_CHECKING
#ifndef NDEBUG
#ifndef FOGL_AUTO_NULL_CHECKING
#define FOGL_AUTO_NULL_CHECKING
#endif
#endif
#endif

#ifdef FOGL_FORCE_AUTO_NULL_CHECKING
#ifndef FOGL_AUTO_NULL_CHECKING
#define FOGL_AUTO_NULL_CHECKING
#endif
#endif
